### ISSUE TITLE
STU3 support for MedicationStatement component

### ISSUE THREAD

**Issue by ctomasz** [1uphealth/fhir-react#46]
TODO:

Add STU3 support to MedicationStatement component
Add fixtures, tests, storybook stories

**Comment by liam1uphealth** [comment]
- [ ] Can you move the name of the medication to the top. For example, 'Tylenol PM' in the story book, should be at the top rather than 'status active'
- [ ] Can you remove some of the new line separations. if a section has a bold title, no need for a new line below. Generally speaking, we don't want the resources to have a very large height unless there is a significant amount of data, similar to how many encounter resources do. For example, no need for a new line between each element below 
Dosage
Dosage Instruction: 1-2 tablets once daily at bedtime as needed for restless legs

Additional Instruction:Taking at bedtime

Route: Oral Route

**Comment by ctomasz** [comment]
Required changes merged into the `master` branch; The functionality available at `fhir-react` library from `0.1.2` version;
